version: '3.8'

services:
  db-oracle:
    image: kutsyy/oracle-12c
    container_name: db-oracle
    ports:
      - "1521:1521"
    volumes:
      - ./db/script.sql:/docker-entrypoint-initdb.d/script.sql:ro
    environment:
      - ORACLE_PASSWORD=oracle
      - ORACLE_ALLOW_REMOTE=true
    networks:
      - Veranum
    healthcheck:
      test: ["CMD-SHELL", "until nc -z localhost 1521; do echo waiting for oracle; sleep 5; done"]
      interval: 10s
      retries: 30

  server-spring-boot:
    build:
      context: ./Server
      dockerfile: Dockerfile
    container_name: server-spring-boot
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@db-oracle:1521:xe
      - SPRING_DATASOURCE_USERNAME=system
      - SPRING_DATASOURCE_PASSWORD=oracle
    depends_on:
      db-oracle:
        condition: service_healthy
    networks:
      - Veranum

networks:
  Veranum:
    name: Veranum
