BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE USUARIO CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;


BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE PROVEEDOR CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;


BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE PEDIDO_H CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;


BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE PEDIDO_B CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;


BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE PRODUCTO CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;


BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE ORDEN_H CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;


BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE ORDEN_B CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;


BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE PLATILLO CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;


BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE MESA CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;


BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE RESERVA CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;


BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE CLIENTE CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;


BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE DOCUMENTO CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;


BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE INGREDIENTE CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;


-- Create tables with Oracle-friendly types
CREATE TABLE USUARIO
(
        RUT                 NUMBER PRIMARY KEY,
        DV                  CHAR(1) NOT NULL,
        USERNAME            VARCHAR2(70) NOT NULL,
        PASSWORD            VARCHAR2(255) NOT NULL,
        NOMBRE              VARCHAR2(70) NOT NULL,
        APELLIDO            VARCHAR2(70) NOT NULL,
        ROL                 NUMBER NOT NULL,
        CORREO              VARCHAR2(255) NOT NULL,
        FECHA_NACIMIENTO    DATE NOT NULL
);

CREATE TABLE PROVEEDOR 
(
        RUT                 VARCHAR2(15) PRIMARY KEY,
        NOMBRE              VARCHAR2(70) NOT NULL,
        TELEFONO            VARCHAR2(15) NOT NULL,
        DIRECCION           VARCHAR2(255) NOT NULL,
        CORREO              VARCHAR2(255) NOT NULL
);

CREATE TABLE PEDIDO_H 
(
        ID                  NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
        TOTAL               NUMBER NOT NULL,
        ESTADO              NUMBER NOT NULL,
        PROVEEDOR_ID        VARCHAR2(15) NOT NULL,
        DOCUMENTO_ID        NUMBER NOT NULL
);

CREATE TABLE PEDIDO_B
(
        ID                  NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
        CANTIDAD            NUMBER NOT NULL,
        SUBTOTAL            NUMBER NOT NULL,
        PEDIDO_H_ID         NUMBER NOT NULL,
        PRODUCTO_ID         NUMBER NOT NULL
);

CREATE TABLE PRODUCTO 
(
        ID                  NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
        NOMBRE              VARCHAR2(70) NOT NULL,
        DESCRIPCION         VARCHAR2(255) NOT NULL,
        CANTIDAD            NUMBER NOT NULL,
        PRECIO              NUMBER NOT NULL,
        CATEGORIA           VARCHAR2(70) NOT NULL
);

CREATE TABLE DOCUMENTO 
(
        ID                  NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
        FECHA               DATE NOT NULL,
        HORA                VARCHAR2(5),
        TIPO                NUMBER
);

CREATE TABLE ORDEN_H
(
        ID                  NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
        TOTAL               NUMBER NOT NULL,
        ESTADO              NUMBER NOT NULL,
        DOCUMENTO_ID        NUMBER NOT NULL,
        MESA_ID             NUMBER NOT NULL
);

CREATE TABLE ORDEN_B
(
        ID                  NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
        CANTIDAD            NUMBER NOT NULL,
        SUBTOTAL            NUMBER NOT NULL,
        ORDEN_H_ID          NUMBER NOT NULL,
        PLATILLO_ID         NUMBER NOT NULL
);

CREATE TABLE MESA
(
        ID                  NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
        NUMERO              NUMBER NOT NULL,
        CAPACIDAD           NUMBER NOT NULL,
        ESTADO              NUMBER NOT NULL
);

CREATE TABLE CLIENTE
(
        RUT                 NUMBER PRIMARY KEY,
        DV                  CHAR(1) NOT NULL,
        NOMBRE              VARCHAR2(70) NOT NULL,
        APELLIDO            VARCHAR2(70) NOT NULL,
        CORREO              VARCHAR2(255) NOT NULL,
        TELEFONO            VARCHAR2(255) NOT NULL
);

CREATE TABLE RESERVA
(
        ID                  NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
        FECHA               DATE NOT NULL,
        HORA                VARCHAR2(5) NOT NULL,
        CANTIDAD_PERSONAS   NUMBER NOT NULL,
        ESTADO              NUMBER NOT NULL,
        CLIENTE_ID          NUMBER NOT NULL,
        MESA_ID             NUMBER NOT NULL
);

CREATE TABLE PLATILLO
(
        ID                  NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
        NOMBRE              VARCHAR2(70) NOT NULL,
        TIEMPO              NUMBER NOT NULL,
        PRECIO              NUMBER NULL
);

CREATE TABLE INGREDIENTE
(
        ID                  NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
        CANTIDAD            NUMBER NOT NULL,
        PLATILLO_ID         NUMBER NOT NULL,
        PRODUCTO_ID         NUMBER NOT NULL
);

-- Foreign key constraints
ALTER TABLE PEDIDO_H ADD CONSTRAINT fk_PEDIDO_H_DOCUMENTO FOREIGN KEY (DOCUMENTO_ID) 
REFERENCES DOCUMENTO(ID);

ALTER TABLE PEDIDO_H ADD CONSTRAINT fk_PEDIDO_H_PROVEEDOR FOREIGN KEY (PROVEEDOR_ID) 
REFERENCES PROVEEDOR(RUT);

ALTER TABLE PEDIDO_B ADD CONSTRAINT fk_PEDIDO_B_PEDIDO_H FOREIGN KEY (PEDIDO_H_ID) 
REFERENCES PEDIDO_H(ID);

ALTER TABLE PEDIDO_B ADD CONSTRAINT fk_PEDIDO_B_PRODUCTO FOREIGN KEY (PRODUCTO_ID) 
REFERENCES PRODUCTO(ID);

ALTER TABLE ORDEN_H ADD CONSTRAINT fk_ORDEN_H_DOCUMENTO FOREIGN KEY (DOCUMENTO_ID) 
REFERENCES DOCUMENTO(ID);

ALTER TABLE ORDEN_H ADD CONSTRAINT fk_ORDEN_H_MESA FOREIGN KEY (MESA_ID) 
REFERENCES MESA(ID);

ALTER TABLE ORDEN_B ADD CONSTRAINT fk_ORDEN_B_ORDEN_H FOREIGN KEY (ORDEN_H_ID) 
REFERENCES ORDEN_H(ID);

ALTER TABLE ORDEN_B ADD CONSTRAINT fk_ORDEN_B_PLATILLO FOREIGN KEY (PLATILLO_ID) 
REFERENCES PLATILLO(ID);

ALTER TABLE RESERVA ADD CONSTRAINT fk_RESERVA_MESA FOREIGN KEY (MESA_ID) 
REFERENCES MESA(ID);

ALTER TABLE RESERVA ADD CONSTRAINT fk_RESERVA_CLIENTE FOREIGN KEY (CLIENTE_ID) 
REFERENCES CLIENTE(RUT);

ALTER TABLE INGREDIENTE ADD CONSTRAINT fk_INGREDIENTE_PLATILLO FOREIGN KEY (PLATILLO_ID) 
REFERENCES PLATILLO(ID);

ALTER TABLE INGREDIENTE ADD CONSTRAINT fk_INGREDIENTE_PRODUCTO FOREIGN KEY (PRODUCTO_ID) 
REFERENCES PRODUCTO(ID);

COMMIT;
